#!/bin/bash

#changing the environment to testnet requires changing the json config file

# Params that need to be validated per installation - 
# 	OS system of the downloaded zip
# 	dotnet version
#   user directory - in this case "julia"


#   Installing NEO dependencies
sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev

#   Installing the downloaded ZIP
cd /home/julia/Downloads
sudo unzip neo-cli-ubuntu.16.04-x64.zip -d /opt

#   Installing .NET Core
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.4
dotnet --version

cd /opt/neo-cli

#   Running the CLI
sudo dotnet neo-cli.dll /rpc
